import type { BoardSkin } from "./types";

export const SKINS: Record<string, BoardSkin> = {
  ops: {
    id: "ops",
    name: "OPS Default",
    description: "Стандартная экипировка сапёра. Сталь, бетон, кровь.",
    rarity: "common",
    priceCents: 0,
    priceCoins: 0,
    tokens: {
      "--cell-bg": "var(--steel-800)",
      "--cell-bg-hover": "var(--steel-700)",
      "--cell-bg-open": "var(--bg-elevated)",
      "--cell-border": "var(--steel-900)",
      "--cell-border-open": "var(--bg-void)",
    },
  },
  carbon: {
    id: "carbon",
    name: "Carbon Fiber",
    description: "Карбоновое плетение. Идеально для тех, кто ценит точность.",
    rarity: "rare",
    priceCents: 299,
    priceCoins: 800,
    tokens: {
      "--cell-bg": "#1c1c1c",
      "--cell-bg-hover": "#262626",
      "--cell-bg-open": "#0d0d0d",
      "--cell-border": "#2a2a2a",
      "--cell-border-open": "#000",
      "--num-1": "#ff6b6b",
      "--num-2": "#ff8585",
      "--num-3": "#ff4654",
      "--num-4": "#c0c0c0",
      "--num-5": "#e63946",
      "--num-6": "#ff4654",
      "--num-7": "#8b0000",
      "--num-8": "#fff",
    },
  },
  blueprint: {
    id: "blueprint",
    name: "Blueprint",
    description: "Технический чертёж. Тонкие линии, инженерная точность.",
    rarity: "rare",
    priceCents: 299,
    priceCoins: 800,
    tokens: {
      "--cell-bg": "#0d1f2d",
      "--cell-bg-hover": "#163148",
      "--cell-bg-open": "#081320",
      "--cell-border": "#1c3a52",
      "--cell-border-open": "#0a1722",
      "--num-1": "#7ec8ff",
      "--num-2": "#a3d5ff",
      "--num-3": "#ff8585",
      "--num-4": "#b5b5d8",
      "--num-5": "#e63946",
      "--num-6": "#ff4654",
      "--num-7": "#fff",
      "--num-8": "#fff",
    },
  },
  neonTokyo: {
    id: "neonTokyo",
    name: "Neon Tokyo",
    description: "Кислотный неон и киберпанк. Не для слабонервных.",
    rarity: "epic",
    priceCents: 399,
    priceCoins: 1500,
    tokens: {
      "--cell-bg": "#0a0014",
      "--cell-bg-hover": "#15002a",
      "--cell-bg-open": "#050008",
      "--cell-border": "#ff003c",
      "--cell-border-open": "#1a0a25",
      "--num-1": "#ff003c",
      "--num-2": "#ff00ff",
      "--num-3": "#ff5050",
      "--num-4": "#00ffff",
      "--num-5": "#ff003c",
      "--num-6": "#ff00aa",
      "--num-7": "#ffffff",
      "--num-8": "#ffffff",
    },
  },
  vintage: {
    id: "vintage",
    name: "Vintage War",
    description: "Сепия, военные карты, рукописные пометки красными чернилами.",
    rarity: "epic",
    priceCents: 249,
    priceCoins: 1200,
    tokens: {
      "--cell-bg": "#3d2f1f",
      "--cell-bg-hover": "#4d3d28",
      "--cell-bg-open": "#2a2014",
      "--cell-border": "#5c4a30",
      "--cell-border-open": "#1c1408",
      "--num-1": "#d4b896",
      "--num-2": "#c4a878",
      "--num-3": "#ff4654",
      "--num-4": "#a89066",
      "--num-5": "#e63946",
      "--num-6": "#ff4654",
      "--num-7": "#8b0000",
      "--num-8": "#f5e5c0",
    },
  },
  ink: {
    id: "ink",
    name: "Ink Wash",
    description: "Японская тушь на белой рисовой бумаге. Минимализм по-самурайски.",
    rarity: "rare",
    priceCents: 0,
    priceCoins: 600,
    tokens: {
      "--cell-bg": "#e8e4dc",
      "--cell-bg-hover": "#d8d4cc",
      "--cell-bg-open": "#f5f0e8",
      "--cell-border": "#888880",
      "--cell-border-open": "#cccac5",
      "--num-1": "#2a2a2a",
      "--num-2": "#4a4a4a",
      "--num-3": "#c8302a",
      "--num-4": "#6a6a6a",
      "--num-5": "#a02020",
      "--num-6": "#c8302a",
      "--num-7": "#1a1a1a",
      "--num-8": "#000000",
    },
  },
  glass: {
    id: "glass",
    name: "Glass [PRO]",
    description: "Эксклюзив для Pro. Матовое стекло, тонкие тени, прозрачность.",
    rarity: "legendary",
    priceCents: 0,
    priceCoins: 0,
    proOnly: true,
    tokens: {
      "--cell-bg": "rgba(255,255,255,0.06)",
      "--cell-bg-hover": "rgba(255,255,255,0.12)",
      "--cell-bg-open": "rgba(0,0,0,0.3)",
      "--cell-border": "rgba(255,255,255,0.1)",
      "--cell-border-open": "rgba(255,255,255,0.05)",
      "--num-1": "#ff8585",
      "--num-2": "#ffaaaa",
      "--num-3": "#ff4654",
      "--num-4": "#ccccdd",
      "--num-5": "#e63946",
      "--num-6": "#ff4654",
      "--num-7": "#ffffff",
      "--num-8": "#ffffff",
    },
  },
};

export const DEFAULT_SKIN_ID = "ops";

export function getSkin(id: string | null | undefined): BoardSkin {
  if (!id) return SKINS[DEFAULT_SKIN_ID];
  return SKINS[id] ?? SKINS[DEFAULT_SKIN_ID];
}

export const SKIN_LIST = Object.values(SKINS);
